development:
  adapter: postgresql
  encoding: unicode
  database: heuro-tools_development
  pool: 5
  username:
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: heuro-tools_test
  pool: 5
  username:
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: heuro-tools_production
  pool: 5
  username:
  password:
